// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAMih1m9wMRogioR0kWGiqWNNNYxqFwdM',
    appId: '1:61050908584:android:cbbb60bff51a8d48a1379d',
    messagingSenderId: '61050908584',
    projectId: 'my-gym-track-d976e',
    storageBucket: 'my-gym-track-d976e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPyBiY9ayorLzRN7sDj62p4CKE99dvuj0',
    appId: '1:61050908584:ios:a4b21e6139e9d64fa1379d',
    messagingSenderId: '61050908584',
    projectId: 'my-gym-track-d976e',
    storageBucket: 'my-gym-track-d976e.firebasestorage.app',
    iosBundleId: 'com.example.gymV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2oOzfJzzXLYdYrYjehldXyvWNVfovqB8',
    appId: '1:61050908584:web:1e18055f87eac523a1379d',
    messagingSenderId: '61050908584',
    projectId: 'my-gym-track-d976e',
    authDomain: 'my-gym-track-d976e.firebaseapp.com',
    storageBucket: 'my-gym-track-d976e.firebasestorage.app',
    measurementId: 'G-STXBV5WQ5Q',
  );
}
